# Generated by Django 4.1.3 on 2022-12-08 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='lessor_id',
            field=models.IntegerField(blank=True, default=1),
        ),
    ]
