# Generated by Django 4.1.3 on 2022-12-08 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_contact_lessor_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='lessor_name',
            field=models.CharField(blank=True, default='None', max_length=200),
        ),
        migrations.AddField(
            model_name='contact',
            name='lessor_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='contact',
            name='lessor_id',
            field=models.IntegerField(blank=True, default='None'),
        ),
    ]
