city_choices = {
  'TP. Hồ Chí Minh': 'TP. Hồ Chí Minh',
  'Hà Nội': 'Hà Nội',
  'Đà Nẵng': 'Đà Nẵng',
  'Bình Dương':'Bình Dương',
  'An Giang':'An Giang',
  'Bà Rịa – Vũng Tàu':'Bà Rịa – Vũng Tàu',
  'Bạc Liêu':'Bạc Liêu',
  'Bắc Giang':'Bắc Giang',
  'Bắc Kạn':'Bắc Kạn',
  'Bắc Ninh':'Bắc Ninh',
  'Bến Tre':'Bến Tre',
  'Bình Định':'Bình Định',
  'Bình Phước':'Bình Phước',
  'Bình Thuận':'Bình Thuận',
  'Cà Mau':'Cà Mau',
  'Cao Bằng':'Cao Bằng',
  'Cần Thơ':'Cần Thơ',
  'Đắk Lắk':'Đắk Lắk',
  'Đắk Nông':'	Đắk Nông',
  'Điện Biên':'Điện Biên',
  'Đồng Nai':'Đồng Nai',
  'Đồng Tháp':'Đồng Tháp',
  'Gia Lai':'Gia Lai',
  'Hà Giang':'Hà Giang',
  'Hà Nam':'Hà Nam',
  'Hà Tĩnh':'Hà Tĩnh',
  'Hải Dương':'Hải Dương',
  'Hải Phòng':'Hải Phòng',
  'Hậu Giang':'Hậu Giang',
  'Hòa Bình':'Hòa Bình',
  'Hưng Yên':'Hưng Yên',
  'Khánh Hòa':'Khánh Hòa',
  'Kiên Giang':'Kiên Giang',
  'Kon Tum':'Kon Tum',
  'Lai Châu':'Lai Châu',
  'Lạng Sơn':'Lạng Sơn',
  'Lào Cai':'Lào Cai',
  'Lâm Đồng':'Lâm Đồng',
  'Long An':'Long An',
  'Nam Định':'Nam Định',
  'Nghệ An':'Nghệ An',
  'Ninh Bình':'Ninh Bình',
  'Ninh Thuận':'Ninh Thuận',
  'Phú Thọ':'Phú Thọ',
  'Phú Yên':'Phú Yên',
  'Quảng Bình':'Quảng Bình',
  'Quảng Nam':'Quảng Nam',
  'Quảng Ngãi':'Quảng Ngãi',
  'Quảng Ninh':'Quảng Ninh',
  'Quảng Trị':'Quảng Trị',
  'Sóc Trăng':'Sóc Trăng',
  'Sơn La':'Sơn La',
  'Tây Ninh':'Tây Ninh',
  'Thái Bình':'Thái Bình',
  'Thái Nguyên':'Thái Nguyên',
  'Thanh Hóa':'Thanh Hóa',
  'Thừa Thiên Huế':'Thừa Thiên Huế',
  'Tiền Giang':'Tiền Giang',
  'Trà Vinh':'Trà Vinh',
  'Tuyên Quang':'Tuyên Quang',
  'Vĩnh Long':'Vĩnh Long',
  'Vĩnh Phúc':'Vĩnh Phúc',
  'Yên Bái':'Yên Bái',
}

bedroom_choices = {
  '1':1,
  '2':2,
  '3':3,
  '4':4,
  '5':5,
  '6':6,
  '7':7,
  '8':8,
  '9':9,
  '10':10
  }

price_choices = {
  '1500000':'dưới 1.5 triệu',
  '2000000':'dưới 2 triệu',
  '3000000':'dưới 3 triệu',
  '5000000':'dưới 5 triệu',
  '7000000':'dưới 7 triệu',
  '10000000':'dưới 10 triệu',
  '1':'trên 10 triệu',
}

price_choices1 = {
  ('0', '2000000'):'0 - 2 triệu',
  '2000000,3000000':'2 - 3 triệu',
  '3000000,5000000':'3 - 5 triệu',
  '5000000, 7000000':'5 - 7 triệu',
  '5000000, 10000000':'7 - 10 triệu',
  '10000000, 15000000':'10 - 15 triệu',
  '15000000, 999999999':'trên 15 triệu'

}
area_choices = {
  '20': 'dưới 20 (m2)',
  '30': 'dưới 30 (m2)',
  '50': 'dưới 50 (m2)',
  '70': 'dưới 70 (m2)',
  '90': 'dưới 90 (m2)',
  '1': 'Trên 90 (m2)',
}

