# Generated by Django 4.1.3 on 2022-12-04 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_profile_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(default='avt_default.png', upload_to='photos/%Y/%m/%d'),
        ),
    ]
