# Generated by Django 4.1.3 on 2022-12-02 04:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('address', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('price', models.IntegerField()),
                ('area', models.IntegerField()),
                ('bedrooms', models.IntegerField()),
                ('badrooms', models.IntegerField()),
                ('floors', models.IntegerField()),
                ('furniture', models.TextField(blank=True)),
                ('list_date', models.DateField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
