# Generated by Django 4.1.3 on 2022-12-02 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0002_listing_delete_house'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='area',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='badrooms',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='bedrooms',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='floors',
        ),
    ]
