# Generated by Django 4.1.3 on 2022-12-02 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0004_listing_securitysystem_listing_aircondition_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='ComunityCenter',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='listing',
            name='SecuritySystem',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='listing',
            name='aircondition',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='listing',
            name='bathrooms',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='listing',
            name='bedrooms',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='listing',
            name='furniture',
            field=models.TextField(default=0),
        ),
        migrations.AlterField(
            model_name='listing',
            name='kitcheen',
            field=models.IntegerField(default=0),
        ),
    ]
