# Generated by Django 4.1.3 on 2022-12-02 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0005_listing_comunitycenter_alter_listing_securitysystem_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='aircondition',
            new_name='AirCondition',
        ),
        migrations.RenameField(
            model_name='listing',
            old_name='furniture',
            new_name='Furniture',
        ),
        migrations.AddField(
            model_name='listing',
            name='city',
            field=models.CharField(default='HCM', max_length=100),
        ),
        migrations.AddField(
            model_name='listing',
            name='floor',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='listing',
            name='garage',
            field=models.IntegerField(default=0),
        ),
    ]
