# Generated by Django 4.1.3 on 2022-12-02 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0006_rename_aircondition_listing_aircondition_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='garage',
            field=models.BooleanField(default=0),
        ),
    ]
