# Generated by Django 4.1.3 on 2022-12-04 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0007_alter_listing_garage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='photo_main',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/'),
        ),
    ]
