# Generated by Django 4.1.3 on 2022-12-05 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0011_listing_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='status',
            field=models.CharField(choices=[('Available', 'Available'), ('Unvailable', 'Unavailable'), ('Sale', 'For Sale')], default='Available', max_length=20),
        ),
    ]
