# Generated by Django 4.1.3 on 2022-12-05 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0012_alter_listing_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='city',
            field=models.CharField(choices=[('TP. Hồ Chí Minh', 'TP. Hồ Chí Minh'), ('Đà Nẵng', 'Đà Nẵng'), ('Hà Nội', 'Hà Nội')], default='TP. Hồ Chí Minh', max_length=100),
        ),
    ]
