# Generated by Django 4.1.3 on 2022-12-05 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0013_alter_listing_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='city',
            field=models.CharField(choices=[('Ha Noi', 'Hà Nội'), ('TP. Ho Chi Minh', 'TP. Hồ Chí Minh'), ('Da Nang', 'Đà Nẵng')], default='TP. Hồ Chí Minh', max_length=100),
        ),
    ]
