# Generated by Django 4.1.3 on 2022-12-05 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0014_alter_listing_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='city',
            field=models.CharField(choices=[('Hà Nội', 'Hà Nội'), ('Đà Nẵng', 'Đà Nẵng'), ('TP. Hồ Chí Minh', 'TP. Hồ Chí Minh')], default='TP. Hồ Chí Minh', max_length=100),
        ),
    ]
