# Generated by Django 4.1.3 on 2022-12-08 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0015_alter_listing_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='city',
            field=models.CharField(choices=[('Khánh Hòa', 'Khánh Hòa'), ('Nghệ An', 'Nghệ An'), ('Tây Ninh', 'Tây Ninh'), ('Quảng Ninh', 'Quảng Ninh'), ('Phú Thọ', 'Phú Thọ'), ('Hòa Bình', 'Hòa Bình'), ('Kiên Giang', 'Kiên Giang'), ('Lạng Sơn', 'Lạng Sơn'), ('Tuyên Quang', 'Tuyên Quang'), ('Thừa Thiên Huế', 'Thừa Thiên Huế'), ('Bắc Kạn', 'Bắc Kạn'), ('Thái Bình', 'Thái Bình'), ('Hậu Giang', 'Hậu Giang'), ('Thanh Hóa', 'Thanh Hóa'), ('Cần Thơ', 'Cần Thơ'), ('Bình Thuận', 'Bình Thuận'), ('TP. Hồ Chí Minh', 'TP. Hồ Chí Minh'), ('Ninh Thuận', 'Ninh Thuận'), ('Bắc Ninh', 'Bắc Ninh'), ('Long An', 'Long An'), ('Lào Cai', 'Lào Cai'), ('Tiền Giang', 'Tiền Giang'), ('Điện Biên', 'Điện Biên'), ('Đắk Nông', 'Đắk Nông'), ('Lâm Đồng', 'Lâm Đồng'), ('Quảng Bình', 'Quảng Bình'), ('Thái Nguyên', 'Thái Nguyên'), ('Sóc Trăng', 'Sóc Trăng'), ('Hải Dương', 'Hải Dương'), ('Hà Nam', 'Hà Nam'), ('Gia Lai', 'Gia Lai'), ('Đồng Nai', 'Đồng Nai'), ('Bình Dương', 'Bình Dương'), ('Bình Định', 'Bình Định'), ('Kon Tum', 'Kon Tum'), ('Sơn La', 'Sơn La'), ('Bạc Liêu', 'Bạc Liêu'), ('Hà Giang', 'Hà Giang'), ('Trà Vinh', 'Trà Vinh'), ('An Giang', 'An Giang'), ('Ninh Bình', 'Ninh Bình'), ('Bắc Giang', 'Bắc Giang'), ('Hải Phòng', 'Hải Phòng'), ('Nam Định', 'Nam Định'), ('Vĩnh Phúc', 'Vĩnh Phúc'), ('Đắk Lắk', 'Đắk Lắk'), ('Quảng Ngãi', 'Quảng Ngãi'), ('Quảng Nam', 'Quảng Nam'), ('Hưng Yên', 'Hưng Yên'), ('Hà Tĩnh', 'Hà Tĩnh'), ('Phú Yên', 'Phú Yên'), ('Bà Rịa – Vũng Tàu', 'Bà Rịa – Vũng Tàu'), ('Cà Mau', 'Cà Mau'), ('Bến Tre', 'Bến Tre'), ('Hà Nội', 'Hà Nội'), ('Yên Bái', 'Yên Bái'), ('Lai Châu', 'Lai Châu'), ('Cao Bằng', 'Cao Bằng'), ('Đà Nẵng', 'Đà Nẵng'), ('Quảng Trị', 'Quảng Trị'), ('Bình Phước', 'Bình Phước'), ('Đồng Tháp', 'Đồng Tháp'), ('Vĩnh Long', 'Vĩnh Long')], default='TP. Hồ Chí Minh', max_length=100),
        ),
    ]
