# Generated by Django 4.1.3 on 2022-12-08 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0017_alter_listing_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='city',
            field=models.CharField(choices=[('Đắk Nông', 'Đắk Nông'), ('Vĩnh Long', 'Vĩnh Long'), ('An Giang', 'An Giang'), ('Hà Nam', 'Hà Nam'), ('Tiền Giang', 'Tiền Giang'), ('Yên Bái', 'Yên Bái'), ('Bình Dương', 'Bình Dương'), ('Thừa Thiên Huế', 'Thừa Thiên Huế'), ('Lào Cai', 'Lào Cai'), ('Thái Bình', 'Thái Bình'), ('Bình Thuận', 'Bình Thuận'), ('Cà Mau', 'Cà Mau'), ('Nam Định', 'Nam Định'), ('Thái Nguyên', 'Thái Nguyên'), ('Trà Vinh', 'Trà Vinh'), ('Bình Định', 'Bình Định'), ('Bắc Kạn', 'Bắc Kạn'), ('Bà Rịa – Vũng Tàu', 'Bà Rịa – Vũng Tàu'), ('Hải Phòng', 'Hải Phòng'), ('Hà Tĩnh', 'Hà Tĩnh'), ('Sóc Trăng', 'Sóc Trăng'), ('Đồng Tháp', 'Đồng Tháp'), ('Lâm Đồng', 'Lâm Đồng'), ('Tây Ninh', 'Tây Ninh'), ('Phú Thọ', 'Phú Thọ'), ('Đắk Lắk', 'Đắk Lắk'), ('Hà Giang', 'Hà Giang'), ('Bình Phước', 'Bình Phước'), ('Ninh Bình', 'Ninh Bình'), ('Nghệ An', 'Nghệ An'), ('Bắc Giang', 'Bắc Giang'), ('Hòa Bình', 'Hòa Bình'), ('Hậu Giang', 'Hậu Giang'), ('Quảng Trị', 'Quảng Trị'), ('TP. Hồ Chí Minh', 'TP. Hồ Chí Minh'), ('Lai Châu', 'Lai Châu'), ('Hưng Yên', 'Hưng Yên'), ('Hà Nội', 'Hà Nội'), ('Phú Yên', 'Phú Yên'), ('Hải Dương', 'Hải Dương'), ('Bến Tre', 'Bến Tre'), ('Kiên Giang', 'Kiên Giang'), ('Bắc Ninh', 'Bắc Ninh'), ('Cao Bằng', 'Cao Bằng'), ('Long An', 'Long An'), ('Bạc Liêu', 'Bạc Liêu'), ('Sơn La', 'Sơn La'), ('Đồng Nai', 'Đồng Nai'), ('Vĩnh Phúc', 'Vĩnh Phúc'), ('Quảng Ngãi', 'Quảng Ngãi'), ('Kon Tum', 'Kon Tum'), ('Quảng Bình', 'Quảng Bình'), ('Cần Thơ', 'Cần Thơ'), ('Tuyên Quang', 'Tuyên Quang'), ('Điện Biên', 'Điện Biên'), ('Đà Nẵng', 'Đà Nẵng'), ('Lạng Sơn', 'Lạng Sơn'), ('Ninh Thuận', 'Ninh Thuận'), ('Thanh Hóa', 'Thanh Hóa'), ('Quảng Ninh', 'Quảng Ninh'), ('Gia Lai', 'Gia Lai'), ('Quảng Nam', 'Quảng Nam'), ('Khánh Hòa', 'Khánh Hòa')], default='TP. Hồ Chí Minh', max_length=100),
        ),
    ]
