# Generated by Django 4.1.3 on 2022-12-08 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0018_alter_listing_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='city',
            field=models.CharField(choices=[('Đắk Lắk', 'Đắk Lắk'), ('Cần Thơ', 'Cần Thơ'), ('Thái Bình', 'Thái Bình'), ('Bạc Liêu', 'Bạc Liêu'), ('Sóc Trăng', 'Sóc Trăng'), ('Bình Dương', 'Bình Dương'), ('Bình Thuận', 'Bình Thuận'), ('Vĩnh Long', 'Vĩnh Long'), ('Đồng Nai', 'Đồng Nai'), ('Sơn La', 'Sơn La'), ('Bình Định', 'Bình Định'), ('Bà Rịa – Vũng Tàu', 'Bà Rịa – Vũng Tàu'), ('Gia Lai', 'Gia Lai'), ('Hà Nội', 'Hà Nội'), ('Lâm Đồng', 'Lâm Đồng'), ('Long An', 'Long An'), ('Bắc Giang', 'Bắc Giang'), ('Hậu Giang', 'Hậu Giang'), ('Lạng Sơn', 'Lạng Sơn'), ('Đà Nẵng', 'Đà Nẵng'), ('An Giang', 'An Giang'), ('Bắc Ninh', 'Bắc Ninh'), ('Hải Dương', 'Hải Dương'), ('Tây Ninh', 'Tây Ninh'), ('Khánh Hòa', 'Khánh Hòa'), ('Đắk Nông', 'Đắk Nông'), ('Thừa Thiên Huế', 'Thừa Thiên Huế'), ('Ninh Thuận', 'Ninh Thuận'), ('Yên Bái', 'Yên Bái'), ('Ninh Bình', 'Ninh Bình'), ('Cà Mau', 'Cà Mau'), ('Bến Tre', 'Bến Tre'), ('Kiên Giang', 'Kiên Giang'), ('Quảng Trị', 'Quảng Trị'), ('Hà Tĩnh', 'Hà Tĩnh'), ('Cao Bằng', 'Cao Bằng'), ('Quảng Ninh', 'Quảng Ninh'), ('TP. Hồ Chí Minh', 'TP. Hồ Chí Minh'), ('Kon Tum', 'Kon Tum'), ('Bình Phước', 'Bình Phước'), ('Hà Giang', 'Hà Giang'), ('Lai Châu', 'Lai Châu'), ('Nghệ An', 'Nghệ An'), ('Vĩnh Phúc', 'Vĩnh Phúc'), ('Nam Định', 'Nam Định'), ('Hưng Yên', 'Hưng Yên'), ('Thanh Hóa', 'Thanh Hóa'), ('Quảng Bình', 'Quảng Bình'), ('Thái Nguyên', 'Thái Nguyên'), ('Trà Vinh', 'Trà Vinh'), ('Tuyên Quang', 'Tuyên Quang'), ('Điện Biên', 'Điện Biên'), ('Bắc Kạn', 'Bắc Kạn'), ('Phú Thọ', 'Phú Thọ'), ('Phú Yên', 'Phú Yên'), ('Quảng Ngãi', 'Quảng Ngãi'), ('Hòa Bình', 'Hòa Bình'), ('Đồng Tháp', 'Đồng Tháp'), ('Hải Phòng', 'Hải Phòng'), ('Hà Nam', 'Hà Nam'), ('Tiền Giang', 'Tiền Giang'), ('Quảng Nam', 'Quảng Nam'), ('Lào Cai', 'Lào Cai')], default='TP. Hồ Chí Minh', max_length=100),
        ),
    ]
