# Generated by Django 4.1.3 on 2022-12-08 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0019_alter_listing_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='city',
            field=models.CharField(choices=[('TP. Hồ Chí Minh', 'TP. Hồ Chí Minh'), ('Bắc Kạn', 'Bắc Kạn'), ('Quảng Ninh', 'Quảng Ninh'), ('Bến Tre', 'Bến Tre'), ('Tuyên Quang', 'Tuyên Quang'), ('Lạng Sơn', 'Lạng Sơn'), ('Long An', 'Long An'), ('Lâm Đồng', 'Lâm Đồng'), ('Tiền Giang', 'Tiền Giang'), ('Khánh Hòa', 'Khánh Hòa'), ('Trà Vinh', 'Trà Vinh'), ('Hậu Giang', 'Hậu Giang'), ('Nghệ An', 'Nghệ An'), ('Hưng Yên', 'Hưng Yên'), ('Thanh Hóa', 'Thanh Hóa'), ('Cần Thơ', 'Cần Thơ'), ('Hải Phòng', 'Hải Phòng'), ('Thái Nguyên', 'Thái Nguyên'), ('Bình Định', 'Bình Định'), ('Lào Cai', 'Lào Cai'), ('Cao Bằng', 'Cao Bằng'), ('Ninh Bình', 'Ninh Bình'), ('Bà Rịa – Vũng Tàu', 'Bà Rịa – Vũng Tàu'), ('Vĩnh Long', 'Vĩnh Long'), ('Bình Thuận', 'Bình Thuận'), ('Bình Phước', 'Bình Phước'), ('Hòa Bình', 'Hòa Bình'), ('Yên Bái', 'Yên Bái'), ('Bắc Ninh', 'Bắc Ninh'), ('Ninh Thuận', 'Ninh Thuận'), ('Tây Ninh', 'Tây Ninh'), ('Bắc Giang', 'Bắc Giang'), ('Điện Biên', 'Điện Biên'), ('Quảng Ngãi', 'Quảng Ngãi'), ('Quảng Nam', 'Quảng Nam'), ('Sơn La', 'Sơn La'), ('Phú Yên', 'Phú Yên'), ('Phú Thọ', 'Phú Thọ'), ('Đồng Tháp', 'Đồng Tháp'), ('Kiên Giang', 'Kiên Giang'), ('Hà Nội', 'Hà Nội'), ('Đắk Lắk', 'Đắk Lắk'), ('Hải Dương', 'Hải Dương'), ('Quảng Trị', 'Quảng Trị'), ('Đắk Nông', 'Đắk Nông'), ('Gia Lai', 'Gia Lai'), ('Kon Tum', 'Kon Tum'), ('Thừa Thiên Huế', 'Thừa Thiên Huế'), ('Bạc Liêu', 'Bạc Liêu'), ('Hà Giang', 'Hà Giang'), ('An Giang', 'An Giang'), ('Hà Nam', 'Hà Nam'), ('Lai Châu', 'Lai Châu'), ('Vĩnh Phúc', 'Vĩnh Phúc'), ('Đà Nẵng', 'Đà Nẵng'), ('Cà Mau', 'Cà Mau'), ('Nam Định', 'Nam Định'), ('Sóc Trăng', 'Sóc Trăng'), ('Bình Dương', 'Bình Dương'), ('Đồng Nai', 'Đồng Nai'), ('Thái Bình', 'Thái Bình'), ('Quảng Bình', 'Quảng Bình'), ('Hà Tĩnh', 'Hà Tĩnh')], default='TP. Hồ Chí Minh', max_length=100),
        ),
    ]
