# Generated by Django 4.1.3 on 2022-12-08 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0020_alter_listing_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='city',
            field=models.CharField(choices=[('Hậu Giang', 'Hậu Giang'), ('Bạc Liêu', 'Bạc Liêu'), ('Quảng Nam', 'Quảng Nam'), ('Tuyên Quang', 'Tuyên Quang'), ('Trà Vinh', 'Trà Vinh'), ('Khánh Hòa', 'Khánh Hòa'), ('Đồng Tháp', 'Đồng Tháp'), ('Bình Phước', 'Bình Phước'), ('An Giang', 'An Giang'), ('Thái Nguyên', 'Thái Nguyên'), ('Quảng Trị', 'Quảng Trị'), ('Bắc Giang', 'Bắc Giang'), ('Phú Yên', 'Phú Yên'), ('Tây Ninh', 'Tây Ninh'), ('Cà Mau', 'Cà Mau'), ('Bình Định', 'Bình Định'), ('Gia Lai', 'Gia Lai'), ('Thái Bình', 'Thái Bình'), ('Nam Định', 'Nam Định'), ('Đồng Nai', 'Đồng Nai'), ('Long An', 'Long An'), ('Hải Dương', 'Hải Dương'), ('Hà Tĩnh', 'Hà Tĩnh'), ('Tiền Giang', 'Tiền Giang'), ('Lai Châu', 'Lai Châu'), ('Đắk Nông', 'Đắk Nông'), ('Sóc Trăng', 'Sóc Trăng'), ('Cao Bằng', 'Cao Bằng'), ('Điện Biên', 'Điện Biên'), ('Lào Cai', 'Lào Cai'), ('Hải Phòng', 'Hải Phòng'), ('Đắk Lắk', 'Đắk Lắk'), ('Bình Dương', 'Bình Dương'), ('Kon Tum', 'Kon Tum'), ('Bến Tre', 'Bến Tre'), ('Vĩnh Long', 'Vĩnh Long'), ('Đà Nẵng', 'Đà Nẵng'), ('TP. Hồ Chí Minh', 'TP. Hồ Chí Minh'), ('Sơn La', 'Sơn La'), ('Hà Giang', 'Hà Giang'), ('Vĩnh Phúc', 'Vĩnh Phúc'), ('Hòa Bình', 'Hòa Bình'), ('Bình Thuận', 'Bình Thuận'), ('Nghệ An', 'Nghệ An'), ('Kiên Giang', 'Kiên Giang'), ('Bắc Kạn', 'Bắc Kạn'), ('Ninh Thuận', 'Ninh Thuận'), ('Quảng Ngãi', 'Quảng Ngãi'), ('Bắc Ninh', 'Bắc Ninh'), ('Phú Thọ', 'Phú Thọ'), ('Lạng Sơn', 'Lạng Sơn'), ('Quảng Bình', 'Quảng Bình'), ('Quảng Ninh', 'Quảng Ninh'), ('Thừa Thiên Huế', 'Thừa Thiên Huế'), ('Bà Rịa – Vũng Tàu', 'Bà Rịa – Vũng Tàu'), ('Lâm Đồng', 'Lâm Đồng'), ('Hà Nam', 'Hà Nam'), ('Yên Bái', 'Yên Bái'), ('Ninh Bình', 'Ninh Bình'), ('Cần Thơ', 'Cần Thơ'), ('Hưng Yên', 'Hưng Yên'), ('Hà Nội', 'Hà Nội'), ('Thanh Hóa', 'Thanh Hóa')], default='TP. Hồ Chí Minh', max_length=100),
        ),
    ]
