# Generated by Django 4.1.3 on 2022-12-08 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0021_alter_listing_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='city',
            field=models.CharField(choices=[('Thái Nguyên', 'Thái Nguyên'), ('Hậu Giang', 'Hậu Giang'), ('Hà Nội', 'Hà Nội'), ('Đồng Nai', 'Đồng Nai'), ('Tuyên Quang', 'Tuyên Quang'), ('Điện Biên', 'Điện Biên'), ('Lai Châu', 'Lai Châu'), ('Hà Nam', 'Hà Nam'), ('Cao Bằng', 'Cao Bằng'), ('Long An', 'Long An'), ('Phú Thọ', 'Phú Thọ'), ('Bắc Kạn', 'Bắc Kạn'), ('Bắc Giang', 'Bắc Giang'), ('Bến Tre', 'Bến Tre'), ('Đắk Nông', 'Đắk Nông'), ('Bình Phước', 'Bình Phước'), ('Lâm Đồng', 'Lâm Đồng'), ('Gia Lai', 'Gia Lai'), ('Khánh Hòa', 'Khánh Hòa'), ('Bạc Liêu', 'Bạc Liêu'), ('Bình Dương', 'Bình Dương'), ('Ninh Bình', 'Ninh Bình'), ('Trà Vinh', 'Trà Vinh'), ('Bắc Ninh', 'Bắc Ninh'), ('Sóc Trăng', 'Sóc Trăng'), ('Hà Giang', 'Hà Giang'), ('Vĩnh Long', 'Vĩnh Long'), ('Hải Dương', 'Hải Dương'), ('Hưng Yên', 'Hưng Yên'), ('Đắk Lắk', 'Đắk Lắk'), ('Ninh Thuận', 'Ninh Thuận'), ('Quảng Bình', 'Quảng Bình'), ('TP. Hồ Chí Minh', 'TP. Hồ Chí Minh'), ('Quảng Ninh', 'Quảng Ninh'), ('Yên Bái', 'Yên Bái'), ('Quảng Ngãi', 'Quảng Ngãi'), ('Sơn La', 'Sơn La'), ('Thừa Thiên Huế', 'Thừa Thiên Huế'), ('Kon Tum', 'Kon Tum'), ('Nghệ An', 'Nghệ An'), ('Hà Tĩnh', 'Hà Tĩnh'), ('Quảng Nam', 'Quảng Nam'), ('An Giang', 'An Giang'), ('Hải Phòng', 'Hải Phòng'), ('Bình Thuận', 'Bình Thuận'), ('Phú Yên', 'Phú Yên'), ('Lào Cai', 'Lào Cai'), ('Tây Ninh', 'Tây Ninh'), ('Đà Nẵng', 'Đà Nẵng'), ('Thái Bình', 'Thái Bình'), ('Lạng Sơn', 'Lạng Sơn'), ('Bà Rịa – Vũng Tàu', 'Bà Rịa – Vũng Tàu'), ('Kiên Giang', 'Kiên Giang'), ('Quảng Trị', 'Quảng Trị'), ('Cà Mau', 'Cà Mau'), ('Tiền Giang', 'Tiền Giang'), ('Cần Thơ', 'Cần Thơ'), ('Hòa Bình', 'Hòa Bình'), ('Vĩnh Phúc', 'Vĩnh Phúc'), ('Bình Định', 'Bình Định'), ('Thanh Hóa', 'Thanh Hóa'), ('Đồng Tháp', 'Đồng Tháp'), ('Nam Định', 'Nam Định')], default='TP. Hồ Chí Minh', max_length=100),
        ),
    ]
