# Generated by Django 4.1.3 on 2022-12-08 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0023_alter_listing_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='city',
            field=models.CharField(choices=[('Nghệ An', 'Nghệ An'), ('Ninh Bình', 'Ninh Bình'), ('Hà Tĩnh', 'Hà Tĩnh'), ('Khánh Hòa', 'Khánh Hòa'), ('Bắc Kạn', 'Bắc Kạn'), ('Hà Nam', 'Hà Nam'), ('Bình Thuận', 'Bình Thuận'), ('Hà Giang', 'Hà Giang'), ('Tuyên Quang', 'Tuyên Quang'), ('Bà Rịa – Vũng Tàu', 'Bà Rịa – Vũng Tàu'), ('Bạc Liêu', 'Bạc Liêu'), ('Tiền Giang', 'Tiền Giang'), ('Trà Vinh', 'Trà Vinh'), ('Cao Bằng', 'Cao Bằng'), ('Yên Bái', 'Yên Bái'), ('Thanh Hóa', 'Thanh Hóa'), ('An Giang', 'An Giang'), ('Phú Yên', 'Phú Yên'), ('Hải Phòng', 'Hải Phòng'), ('Lào Cai', 'Lào Cai'), ('Điện Biên', 'Điện Biên'), ('Sóc Trăng', 'Sóc Trăng'), ('Đắk Nông', 'Đắk Nông'), ('Phú Thọ', 'Phú Thọ'), ('Tây Ninh', 'Tây Ninh'), ('Thái Bình', 'Thái Bình'), ('Quảng Ngãi', 'Quảng Ngãi'), ('Đồng Tháp', 'Đồng Tháp'), ('Gia Lai', 'Gia Lai'), ('Quảng Nam', 'Quảng Nam'), ('Hưng Yên', 'Hưng Yên'), ('Đắk Lắk', 'Đắk Lắk'), ('Bình Phước', 'Bình Phước'), ('Hòa Bình', 'Hòa Bình'), ('Hải Dương', 'Hải Dương'), ('Lai Châu', 'Lai Châu'), ('Sơn La', 'Sơn La'), ('Thái Nguyên', 'Thái Nguyên'), ('Quảng Bình', 'Quảng Bình'), ('Bắc Giang', 'Bắc Giang'), ('Quảng Ninh', 'Quảng Ninh'), ('Quảng Trị', 'Quảng Trị'), ('Lâm Đồng', 'Lâm Đồng'), ('Vĩnh Long', 'Vĩnh Long'), ('TP. Hồ Chí Minh', 'TP. Hồ Chí Minh'), ('Long An', 'Long An'), ('Cà Mau', 'Cà Mau'), ('Hậu Giang', 'Hậu Giang'), ('Hà Nội', 'Hà Nội'), ('Lạng Sơn', 'Lạng Sơn'), ('Nam Định', 'Nam Định'), ('Bình Dương', 'Bình Dương'), ('Bình Định', 'Bình Định'), ('Thừa Thiên Huế', 'Thừa Thiên Huế'), ('Kon Tum', 'Kon Tum'), ('Đồng Nai', 'Đồng Nai'), ('Vĩnh Phúc', 'Vĩnh Phúc'), ('Bến Tre', 'Bến Tre'), ('Bắc Ninh', 'Bắc Ninh'), ('Kiên Giang', 'Kiên Giang'), ('Đà Nẵng', 'Đà Nẵng'), ('Ninh Thuận', 'Ninh Thuận'), ('Cần Thơ', 'Cần Thơ')], default='TP. Hồ Chí Minh', max_length=100),
        ),
    ]
