# Generated by Django 4.1.3 on 2022-12-18 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0025_alter_listing_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='city',
            field=models.CharField(choices=[('Bình Phước', 'Bình Phước'), ('Bình Dương', 'Bình Dương'), ('Kon Tum', 'Kon Tum'), ('Khánh Hòa', 'Khánh Hòa'), ('Hải Dương', 'Hải Dương'), ('Lào Cai', 'Lào Cai'), ('Quảng Bình', 'Quảng Bình'), ('Tiền Giang', 'Tiền Giang'), ('Đồng Tháp', 'Đồng Tháp'), ('Vĩnh Long', 'Vĩnh Long'), ('Hậu Giang', 'Hậu Giang'), ('Lai Châu', 'Lai Châu'), ('Hà Nội', 'Hà Nội'), ('Sơn La', 'Sơn La'), ('Vĩnh Phúc', 'Vĩnh Phúc'), ('TP. Hồ Chí Minh', 'TP. Hồ Chí Minh'), ('Thái Bình', 'Thái Bình'), ('Cà Mau', 'Cà Mau'), ('Quảng Nam', 'Quảng Nam'), ('Hà Nam', 'Hà Nam'), ('An Giang', 'An Giang'), ('Cần Thơ', 'Cần Thơ'), ('Gia Lai', 'Gia Lai'), ('Thừa Thiên Huế', 'Thừa Thiên Huế'), ('Tuyên Quang', 'Tuyên Quang'), ('Bình Định', 'Bình Định'), ('Quảng Trị', 'Quảng Trị'), ('Hà Tĩnh', 'Hà Tĩnh'), ('Đắk Lắk', 'Đắk Lắk'), ('Đồng Nai', 'Đồng Nai'), ('Bà Rịa – Vũng Tàu', 'Bà Rịa – Vũng Tàu'), ('Hòa Bình', 'Hòa Bình'), ('Cao Bằng', 'Cao Bằng'), ('Tây Ninh', 'Tây Ninh'), ('Sóc Trăng', 'Sóc Trăng'), ('Điện Biên', 'Điện Biên'), ('Đắk Nông', 'Đắk Nông'), ('Ninh Thuận', 'Ninh Thuận'), ('Phú Yên', 'Phú Yên'), ('Bắc Ninh', 'Bắc Ninh'), ('Kiên Giang', 'Kiên Giang'), ('Thanh Hóa', 'Thanh Hóa'), ('Bắc Kạn', 'Bắc Kạn'), ('Yên Bái', 'Yên Bái'), ('Bắc Giang', 'Bắc Giang'), ('Nam Định', 'Nam Định'), ('Nghệ An', 'Nghệ An'), ('Ninh Bình', 'Ninh Bình'), ('Đà Nẵng', 'Đà Nẵng'), ('Quảng Ngãi', 'Quảng Ngãi'), ('Bạc Liêu', 'Bạc Liêu'), ('Lạng Sơn', 'Lạng Sơn'), ('Quảng Ninh', 'Quảng Ninh'), ('Trà Vinh', 'Trà Vinh'), ('Bến Tre', 'Bến Tre'), ('Thái Nguyên', 'Thái Nguyên'), ('Bình Thuận', 'Bình Thuận'), ('Long An', 'Long An'), ('Hải Phòng', 'Hải Phòng'), ('Hà Giang', 'Hà Giang'), ('Lâm Đồng', 'Lâm Đồng'), ('Phú Thọ', 'Phú Thọ'), ('Hưng Yên', 'Hưng Yên')], default='null', max_length=100),
        ),
    ]
