# Generated by Django 4.1.3 on 2022-12-18 06:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('house', '0026_alter_listing_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='favourites',
            field=models.ManyToManyField(blank=True, default=None, related_name='favourite', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='listing',
            name='city',
            field=models.CharField(choices=[('Quảng Ngãi', 'Quảng Ngãi'), ('Điện Biên', 'Điện Biên'), ('Tiền Giang', 'Tiền Giang'), ('Tây Ninh', 'Tây Ninh'), ('Hải Phòng', 'Hải Phòng'), ('Lai Châu', 'Lai Châu'), ('Bình Phước', 'Bình Phước'), ('Ninh Thuận', 'Ninh Thuận'), ('Kon Tum', 'Kon Tum'), ('Hà Giang', 'Hà Giang'), ('Khánh Hòa', 'Khánh Hòa'), ('Long An', 'Long An'), ('Đắk Lắk', 'Đắk Lắk'), ('Nghệ An', 'Nghệ An'), ('Đồng Nai', 'Đồng Nai'), ('Bến Tre', 'Bến Tre'), ('Đồng Tháp', 'Đồng Tháp'), ('Thái Nguyên', 'Thái Nguyên'), ('Bình Định', 'Bình Định'), ('Hà Tĩnh', 'Hà Tĩnh'), ('Đắk Nông', 'Đắk Nông'), ('Cao Bằng', 'Cao Bằng'), ('Bắc Ninh', 'Bắc Ninh'), ('Lâm Đồng', 'Lâm Đồng'), ('Ninh Bình', 'Ninh Bình'), ('An Giang', 'An Giang'), ('Bắc Giang', 'Bắc Giang'), ('Hà Nam', 'Hà Nam'), ('Hòa Bình', 'Hòa Bình'), ('Cần Thơ', 'Cần Thơ'), ('Đà Nẵng', 'Đà Nẵng'), ('Lào Cai', 'Lào Cai'), ('Quảng Trị', 'Quảng Trị'), ('TP. Hồ Chí Minh', 'TP. Hồ Chí Minh'), ('Sóc Trăng', 'Sóc Trăng'), ('Yên Bái', 'Yên Bái'), ('Bắc Kạn', 'Bắc Kạn'), ('Lạng Sơn', 'Lạng Sơn'), ('Quảng Bình', 'Quảng Bình'), ('Hà Nội', 'Hà Nội'), ('Bà Rịa – Vũng Tàu', 'Bà Rịa – Vũng Tàu'), ('Thái Bình', 'Thái Bình'), ('Hải Dương', 'Hải Dương'), ('Quảng Nam', 'Quảng Nam'), ('Tuyên Quang', 'Tuyên Quang'), ('Vĩnh Phúc', 'Vĩnh Phúc'), ('Bạc Liêu', 'Bạc Liêu'), ('Sơn La', 'Sơn La'), ('Quảng Ninh', 'Quảng Ninh'), ('Thanh Hóa', 'Thanh Hóa'), ('Nam Định', 'Nam Định'), ('Cà Mau', 'Cà Mau'), ('Bình Thuận', 'Bình Thuận'), ('Vĩnh Long', 'Vĩnh Long'), ('Phú Yên', 'Phú Yên'), ('Trà Vinh', 'Trà Vinh'), ('Thừa Thiên Huế', 'Thừa Thiên Huế'), ('Bình Dương', 'Bình Dương'), ('Gia Lai', 'Gia Lai'), ('Hậu Giang', 'Hậu Giang'), ('Hưng Yên', 'Hưng Yên'), ('Kiên Giang', 'Kiên Giang'), ('Phú Thọ', 'Phú Thọ')], default='null', max_length=100),
        ),
    ]
