# Generated by Django 4.1.3 on 2022-12-18 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0028_alter_listing_managers_alter_listing_city_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='listing',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='listing',
            name='city',
            field=models.CharField(choices=[('Bắc Ninh', 'Bắc Ninh'), ('Đắk Lắk', 'Đắk Lắk'), ('Đắk Nông', 'Đắk Nông'), ('Lâm Đồng', 'Lâm Đồng'), ('Thái Bình', 'Thái Bình'), ('Kiên Giang', 'Kiên Giang'), ('Cao Bằng', 'Cao Bằng'), ('Bình Định', 'Bình Định'), ('Bạc Liêu', 'Bạc Liêu'), ('Hòa Bình', 'Hòa Bình'), ('Nam Định', 'Nam Định'), ('Long An', 'Long An'), ('Quảng Bình', 'Quảng Bình'), ('Vĩnh Phúc', 'Vĩnh Phúc'), ('Quảng Nam', 'Quảng Nam'), ('Ninh Thuận', 'Ninh Thuận'), ('Yên Bái', 'Yên Bái'), ('Hưng Yên', 'Hưng Yên'), ('Đồng Nai', 'Đồng Nai'), ('Hà Nam', 'Hà Nam'), ('Hậu Giang', 'Hậu Giang'), ('Thái Nguyên', 'Thái Nguyên'), ('Bắc Kạn', 'Bắc Kạn'), ('Bình Thuận', 'Bình Thuận'), ('Bà Rịa – Vũng Tàu', 'Bà Rịa – Vũng Tàu'), ('Gia Lai', 'Gia Lai'), ('Vĩnh Long', 'Vĩnh Long'), ('Quảng Ngãi', 'Quảng Ngãi'), ('Trà Vinh', 'Trà Vinh'), ('Lai Châu', 'Lai Châu'), ('Thừa Thiên Huế', 'Thừa Thiên Huế'), ('Quảng Ninh', 'Quảng Ninh'), ('Hải Dương', 'Hải Dương'), ('An Giang', 'An Giang'), ('Cần Thơ', 'Cần Thơ'), ('Hà Giang', 'Hà Giang'), ('Hà Nội', 'Hà Nội'), ('Điện Biên', 'Điện Biên'), ('Phú Yên', 'Phú Yên'), ('Tuyên Quang', 'Tuyên Quang'), ('Lạng Sơn', 'Lạng Sơn'), ('Đà Nẵng', 'Đà Nẵng'), ('Ninh Bình', 'Ninh Bình'), ('Hải Phòng', 'Hải Phòng'), ('TP. Hồ Chí Minh', 'TP. Hồ Chí Minh'), ('Sơn La', 'Sơn La'), ('Tây Ninh', 'Tây Ninh'), ('Sóc Trăng', 'Sóc Trăng'), ('Tiền Giang', 'Tiền Giang'), ('Bến Tre', 'Bến Tre'), ('Quảng Trị', 'Quảng Trị'), ('Lào Cai', 'Lào Cai'), ('Bắc Giang', 'Bắc Giang'), ('Phú Thọ', 'Phú Thọ'), ('Cà Mau', 'Cà Mau'), ('Đồng Tháp', 'Đồng Tháp'), ('Bình Dương', 'Bình Dương'), ('Kon Tum', 'Kon Tum'), ('Khánh Hòa', 'Khánh Hòa'), ('Hà Tĩnh', 'Hà Tĩnh'), ('Nghệ An', 'Nghệ An'), ('Bình Phước', 'Bình Phước'), ('Thanh Hóa', 'Thanh Hóa')], default='null', max_length=100),
        ),
    ]
