# Generated by Django 4.1.3 on 2022-12-28 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0031_auto_20221227_1002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='city',
            field=models.CharField(choices=[('Quảng Trị', 'Quảng Trị'), ('Hưng Yên', 'Hưng Yên'), ('Tiền Giang', 'Tiền Giang'), ('Vĩnh Phúc', 'Vĩnh Phúc'), ('Yên Bái', 'Yên Bái'), ('Ninh Bình', 'Ninh Bình'), ('Sóc Trăng', 'Sóc Trăng'), ('Bắc Ninh', 'Bắc Ninh'), ('Ninh Thuận', 'Ninh Thuận'), ('Đắk Nông', 'Đắk Nông'), ('Lào Cai', 'Lào Cai'), ('Tây Ninh', 'Tây Ninh'), ('Cao Bằng', 'Cao Bằng'), ('Kon Tum', 'Kon Tum'), ('Hà Nội', 'Hà Nội'), ('Bà Rịa – Vũng Tàu', 'Bà Rịa – Vũng Tàu'), ('Bình Định', 'Bình Định'), ('Hải Phòng', 'Hải Phòng'), ('Nam Định', 'Nam Định'), ('Hà Nam', 'Hà Nam'), ('Thái Bình', 'Thái Bình'), ('Hà Giang', 'Hà Giang'), ('Khánh Hòa', 'Khánh Hòa'), ('Sơn La', 'Sơn La'), ('Bắc Kạn', 'Bắc Kạn'), ('Bình Phước', 'Bình Phước'), ('Lâm Đồng', 'Lâm Đồng'), ('Long An', 'Long An'), ('Gia Lai', 'Gia Lai'), ('Bến Tre', 'Bến Tre'), ('Kiên Giang', 'Kiên Giang'), ('Cần Thơ', 'Cần Thơ'), ('Lạng Sơn', 'Lạng Sơn'), ('Trà Vinh', 'Trà Vinh'), ('Hải Dương', 'Hải Dương'), ('Quảng Nam', 'Quảng Nam'), ('Đắk Lắk', 'Đắk Lắk'), ('Thái Nguyên', 'Thái Nguyên'), ('Đà Nẵng', 'Đà Nẵng'), ('Bình Thuận', 'Bình Thuận'), ('Tuyên Quang', 'Tuyên Quang'), ('Thanh Hóa', 'Thanh Hóa'), ('Đồng Nai', 'Đồng Nai'), ('Cà Mau', 'Cà Mau'), ('Bắc Giang', 'Bắc Giang'), ('Vĩnh Long', 'Vĩnh Long'), ('Hà Tĩnh', 'Hà Tĩnh'), ('Lai Châu', 'Lai Châu'), ('Điện Biên', 'Điện Biên'), ('Quảng Ninh', 'Quảng Ninh'), ('Thừa Thiên Huế', 'Thừa Thiên Huế'), ('Hậu Giang', 'Hậu Giang'), ('An Giang', 'An Giang'), ('Quảng Bình', 'Quảng Bình'), ('TP. Hồ Chí Minh', 'TP. Hồ Chí Minh'), ('Phú Yên', 'Phú Yên'), ('Bạc Liêu', 'Bạc Liêu'), ('Phú Thọ', 'Phú Thọ'), ('Bình Dương', 'Bình Dương'), ('Quảng Ngãi', 'Quảng Ngãi'), ('Nghệ An', 'Nghệ An'), ('Hòa Bình', 'Hòa Bình'), ('Đồng Tháp', 'Đồng Tháp')], default='null', max_length=100),
        ),
    ]
