# Generated by Django 4.1.3 on 2022-12-29 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0032_alter_listing_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='city',
            field=models.CharField(choices=[('Hà Nam', 'Hà Nam'), ('Bà Rịa – Vũng Tàu', 'Bà Rịa – Vũng Tàu'), ('Hải Dương', 'Hải Dương'), ('Cao Bằng', 'Cao Bằng'), ('Tiền Giang', 'Tiền Giang'), ('Vĩnh Phúc', 'Vĩnh Phúc'), ('Ninh Bình', 'Ninh Bình'), ('Vĩnh Long', 'Vĩnh Long'), ('Điện Biên', 'Điện Biên'), ('Kon Tum', 'Kon Tum'), ('Hà Tĩnh', 'Hà Tĩnh'), ('Quảng Bình', 'Quảng Bình'), ('Hà Giang', 'Hà Giang'), ('Lào Cai', 'Lào Cai'), ('Quảng Ninh', 'Quảng Ninh'), ('Bến Tre', 'Bến Tre'), ('Bình Phước', 'Bình Phước'), ('Bắc Giang', 'Bắc Giang'), ('Kiên Giang', 'Kiên Giang'), ('Phú Thọ', 'Phú Thọ'), ('Quảng Ngãi', 'Quảng Ngãi'), ('Long An', 'Long An'), ('Nam Định', 'Nam Định'), ('Quảng Trị', 'Quảng Trị'), ('Nghệ An', 'Nghệ An'), ('Lai Châu', 'Lai Châu'), ('Tuyên Quang', 'Tuyên Quang'), ('Cần Thơ', 'Cần Thơ'), ('Đồng Tháp', 'Đồng Tháp'), ('Hòa Bình', 'Hòa Bình'), ('Thanh Hóa', 'Thanh Hóa'), ('Đắk Lắk', 'Đắk Lắk'), ('Yên Bái', 'Yên Bái'), ('Bắc Ninh', 'Bắc Ninh'), ('Bạc Liêu', 'Bạc Liêu'), ('Thái Bình', 'Thái Bình'), ('Ninh Thuận', 'Ninh Thuận'), ('Đắk Nông', 'Đắk Nông'), ('Sóc Trăng', 'Sóc Trăng'), ('Bình Dương', 'Bình Dương'), ('Bình Thuận', 'Bình Thuận'), ('Bình Định', 'Bình Định'), ('Thái Nguyên', 'Thái Nguyên'), ('Gia Lai', 'Gia Lai'), ('Sơn La', 'Sơn La'), ('Hà Nội', 'Hà Nội'), ('An Giang', 'An Giang'), ('Hải Phòng', 'Hải Phòng'), ('Lạng Sơn', 'Lạng Sơn'), ('Phú Yên', 'Phú Yên'), ('TP. Hồ Chí Minh', 'TP. Hồ Chí Minh'), ('Đồng Nai', 'Đồng Nai'), ('Đà Nẵng', 'Đà Nẵng'), ('Trà Vinh', 'Trà Vinh'), ('Lâm Đồng', 'Lâm Đồng'), ('Thừa Thiên Huế', 'Thừa Thiên Huế'), ('Quảng Nam', 'Quảng Nam'), ('Hưng Yên', 'Hưng Yên'), ('Cà Mau', 'Cà Mau'), ('Bắc Kạn', 'Bắc Kạn'), ('Hậu Giang', 'Hậu Giang'), ('Tây Ninh', 'Tây Ninh'), ('Khánh Hòa', 'Khánh Hòa')], default='null', max_length=100),
        ),
    ]
