# Generated by Django 4.1.3 on 2022-12-29 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0034_alter_listing_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='city',
            field=models.CharField(choices=[('Bình Định', 'Bình Định'), ('Khánh Hòa', 'Khánh Hòa'), ('Thái Nguyên', 'Thái Nguyên'), ('Yên Bái', 'Yên Bái'), ('Long An', 'Long An'), ('Hưng Yên', 'Hưng Yên'), ('Bến Tre', 'Bến Tre'), ('Hậu Giang', 'Hậu Giang'), ('Tuyên Quang', 'Tuyên Quang'), ('Quảng Nam', 'Quảng Nam'), ('Bạc Liêu', 'Bạc Liêu'), ('Thanh Hóa', 'Thanh Hóa'), ('Tây Ninh', 'Tây Ninh'), ('Vĩnh Phúc', 'Vĩnh Phúc'), ('Ninh Thuận', 'Ninh Thuận'), ('Kiên Giang', 'Kiên Giang'), ('Thái Bình', 'Thái Bình'), ('Trà Vinh', 'Trà Vinh'), ('Đà Nẵng', 'Đà Nẵng'), ('Vĩnh Long', 'Vĩnh Long'), ('Lâm Đồng', 'Lâm Đồng'), ('Bắc Kạn', 'Bắc Kạn'), ('Phú Yên', 'Phú Yên'), ('Gia Lai', 'Gia Lai'), ('Ninh Bình', 'Ninh Bình'), ('Phú Thọ', 'Phú Thọ'), ('Nam Định', 'Nam Định'), ('Bình Phước', 'Bình Phước'), ('Bà Rịa – Vũng Tàu', 'Bà Rịa – Vũng Tàu'), ('Quảng Trị', 'Quảng Trị'), ('Cà Mau', 'Cà Mau'), ('Đồng Nai', 'Đồng Nai'), ('Hải Phòng', 'Hải Phòng'), ('Hà Giang', 'Hà Giang'), ('Kon Tum', 'Kon Tum'), ('Nghệ An', 'Nghệ An'), ('An Giang', 'An Giang'), ('Điện Biên', 'Điện Biên'), ('Hà Nội', 'Hà Nội'), ('Hà Tĩnh', 'Hà Tĩnh'), ('Đắk Lắk', 'Đắk Lắk'), ('Hòa Bình', 'Hòa Bình'), ('Bắc Ninh', 'Bắc Ninh'), ('Bắc Giang', 'Bắc Giang'), ('Cần Thơ', 'Cần Thơ'), ('Lạng Sơn', 'Lạng Sơn'), ('Đồng Tháp', 'Đồng Tháp'), ('Quảng Ngãi', 'Quảng Ngãi'), ('Lai Châu', 'Lai Châu'), ('Sóc Trăng', 'Sóc Trăng'), ('Quảng Ninh', 'Quảng Ninh'), ('Lào Cai', 'Lào Cai'), ('Đắk Nông', 'Đắk Nông'), ('Thừa Thiên Huế', 'Thừa Thiên Huế'), ('Hải Dương', 'Hải Dương'), ('Bình Thuận', 'Bình Thuận'), ('TP. Hồ Chí Minh', 'TP. Hồ Chí Minh'), ('Sơn La', 'Sơn La'), ('Tiền Giang', 'Tiền Giang'), ('Hà Nam', 'Hà Nam'), ('Bình Dương', 'Bình Dương'), ('Quảng Bình', 'Quảng Bình'), ('Cao Bằng', 'Cao Bằng')], default='null', max_length=100),
        ),
    ]
