# Generated by Django 4.1.4 on 2022-12-29 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0035_alter_listing_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='city',
            field=models.CharField(choices=[('Cao Bằng', 'Cao Bằng'), ('Trà Vinh', 'Trà Vinh'), ('Quảng Ngãi', 'Quảng Ngãi'), ('Quảng Ninh', 'Quảng Ninh'), ('Long An', 'Long An'), ('Nghệ An', 'Nghệ An'), ('Sơn La', 'Sơn La'), ('Hưng Yên', 'Hưng Yên'), ('Đắk Nông', 'Đắk Nông'), ('Bình Dương', 'Bình Dương'), ('Bạc Liêu', 'Bạc Liêu'), ('Hà Nam', 'Hà Nam'), ('Tiền Giang', 'Tiền Giang'), ('Thái Bình', 'Thái Bình'), ('Kon Tum', 'Kon Tum'), ('Đà Nẵng', 'Đà Nẵng'), ('Vĩnh Long', 'Vĩnh Long'), ('Bình Phước', 'Bình Phước'), ('Đồng Nai', 'Đồng Nai'), ('An Giang', 'An Giang'), ('Phú Yên', 'Phú Yên'), ('Bắc Giang', 'Bắc Giang'), ('Đồng Tháp', 'Đồng Tháp'), ('Thái Nguyên', 'Thái Nguyên'), ('Ninh Thuận', 'Ninh Thuận'), ('Lai Châu', 'Lai Châu'), ('Nam Định', 'Nam Định'), ('Quảng Nam', 'Quảng Nam'), ('Vĩnh Phúc', 'Vĩnh Phúc'), ('Thừa Thiên Huế', 'Thừa Thiên Huế'), ('Quảng Trị', 'Quảng Trị'), ('Bình Thuận', 'Bình Thuận'), ('Bình Định', 'Bình Định'), ('Điện Biên', 'Điện Biên'), ('Hậu Giang', 'Hậu Giang'), ('Gia Lai', 'Gia Lai'), ('Ninh Bình', 'Ninh Bình'), ('Tây Ninh', 'Tây Ninh'), ('TP. Hồ Chí Minh', 'TP. Hồ Chí Minh'), ('Phú Thọ', 'Phú Thọ'), ('Hòa Bình', 'Hòa Bình'), ('Yên Bái', 'Yên Bái'), ('Bà Rịa – Vũng Tàu', 'Bà Rịa – Vũng Tàu'), ('Cần Thơ', 'Cần Thơ'), ('Sóc Trăng', 'Sóc Trăng'), ('Hà Nội', 'Hà Nội'), ('Bến Tre', 'Bến Tre'), ('Thanh Hóa', 'Thanh Hóa'), ('Hà Tĩnh', 'Hà Tĩnh'), ('Cà Mau', 'Cà Mau'), ('Kiên Giang', 'Kiên Giang'), ('Lạng Sơn', 'Lạng Sơn'), ('Lâm Đồng', 'Lâm Đồng'), ('Tuyên Quang', 'Tuyên Quang'), ('Đắk Lắk', 'Đắk Lắk'), ('Hà Giang', 'Hà Giang'), ('Quảng Bình', 'Quảng Bình'), ('Khánh Hòa', 'Khánh Hòa'), ('Bắc Ninh', 'Bắc Ninh'), ('Bắc Kạn', 'Bắc Kạn'), ('Lào Cai', 'Lào Cai'), ('Hải Dương', 'Hải Dương'), ('Hải Phòng', 'Hải Phòng')], default='null', max_length=100),
        ),
    ]
