# Generated by Django 4.1.4 on 2022-12-29 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0036_alter_listing_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='city',
            field=models.CharField(choices=[('Đắk Nông', 'Đắk Nông'), ('Quảng Nam', 'Quảng Nam'), ('Hải Phòng', 'Hải Phòng'), ('Quảng Bình', 'Quảng Bình'), ('Điện Biên', 'Điện Biên'), ('Sóc Trăng', 'Sóc Trăng'), ('Đồng Tháp', 'Đồng Tháp'), ('Hậu Giang', 'Hậu Giang'), ('Bình Thuận', 'Bình Thuận'), ('Đồng Nai', 'Đồng Nai'), ('Phú Thọ', 'Phú Thọ'), ('Vĩnh Phúc', 'Vĩnh Phúc'), ('Hải Dương', 'Hải Dương'), ('Quảng Trị', 'Quảng Trị'), ('Bắc Ninh', 'Bắc Ninh'), ('Lâm Đồng', 'Lâm Đồng'), ('Bến Tre', 'Bến Tre'), ('Thái Nguyên', 'Thái Nguyên'), ('Cao Bằng', 'Cao Bằng'), ('Hà Giang', 'Hà Giang'), ('Gia Lai', 'Gia Lai'), ('Hưng Yên', 'Hưng Yên'), ('Lai Châu', 'Lai Châu'), ('Quảng Ninh', 'Quảng Ninh'), ('Bà Rịa – Vũng Tàu', 'Bà Rịa – Vũng Tàu'), ('Tiền Giang', 'Tiền Giang'), ('Bạc Liêu', 'Bạc Liêu'), ('Ninh Bình', 'Ninh Bình'), ('Thanh Hóa', 'Thanh Hóa'), ('Bắc Kạn', 'Bắc Kạn'), ('Thừa Thiên Huế', 'Thừa Thiên Huế'), ('Hà Nam', 'Hà Nam'), ('Cần Thơ', 'Cần Thơ'), ('Bắc Giang', 'Bắc Giang'), ('An Giang', 'An Giang'), ('Ninh Thuận', 'Ninh Thuận'), ('Bình Định', 'Bình Định'), ('Vĩnh Long', 'Vĩnh Long'), ('Hà Nội', 'Hà Nội'), ('Lào Cai', 'Lào Cai'), ('Bình Dương', 'Bình Dương'), ('Hòa Bình', 'Hòa Bình'), ('Phú Yên', 'Phú Yên'), ('Nam Định', 'Nam Định'), ('Quảng Ngãi', 'Quảng Ngãi'), ('Nghệ An', 'Nghệ An'), ('Yên Bái', 'Yên Bái'), ('Đà Nẵng', 'Đà Nẵng'), ('Lạng Sơn', 'Lạng Sơn'), ('Cà Mau', 'Cà Mau'), ('TP. Hồ Chí Minh', 'TP. Hồ Chí Minh'), ('Hà Tĩnh', 'Hà Tĩnh'), ('Thái Bình', 'Thái Bình'), ('Sơn La', 'Sơn La'), ('Đắk Lắk', 'Đắk Lắk'), ('Tuyên Quang', 'Tuyên Quang'), ('Bình Phước', 'Bình Phước'), ('Kiên Giang', 'Kiên Giang'), ('Kon Tum', 'Kon Tum'), ('Khánh Hòa', 'Khánh Hòa'), ('Tây Ninh', 'Tây Ninh'), ('Trà Vinh', 'Trà Vinh'), ('Long An', 'Long An')], default='null', max_length=100),
        ),
    ]
